
// === DAFTAR BARANG UI SHOP ===
export const SERVER_SHOP_ITEMS = [
  // === ORES & MINERALS ===
  { name: "Diamond", id: "minecraft:diamond", price: 1000, category: "Ores" },
  { name: "Netherite Ingot", id: "minecraft:netherite_ingot", price: 5000, category: "Ores" },
  { name: "Gold Ingot", id: "minecraft:gold_ingot", price: 100, category: "Ores" },
  { name: "Iron Ingot", id: "minecraft:iron_ingot", price: 50, category: "Ores" },
  { name: "Copper Ingot", id: "minecraft:copper_ingot", price: 25, category: "Ores" },
  { name: "Emerald", id: "minecraft:emerald", price: 500, category: "Ores" },
  { name: "Coal", id: "minecraft:coal", price: 20, category: "Ores" },
  { name: "Charcoal", id: "minecraft:charcoal", price: 15, category: "Ores" },
  { name: "Quartz", id: "minecraft:quartz", price: 40, category: "Ores" },
  { name: "Amethyst Shard", id: "minecraft:amethyst_shard", price: 60, category: "Ores" },
  { name: "Lapis Lazuli", id: "minecraft:lapis_lazuli", price: 30, category: "Ores" },
  { name: "Raw Iron", id: "minecraft:raw_iron", price: 30, category: "Ores" },
  { name: "Raw Gold", id: "minecraft:raw_gold", price: 60, category: "Ores" },
  { name: "Raw Copper", id: "minecraft:raw_copper", price: 15, category: "Ores" },

  // === FOOD & FARMING ===
  { name: "Steak", id: "minecraft:cooked_beef", price: 25, category: "Food" },
  { name: "Cooked Chicken", id: "minecraft:cooked_chicken", price: 20, category: "Food" },
  { name: "Cooked Porkchop", id: "minecraft:cooked_porkchop", price: 25, category: "Food" },
  { name: "Cooked Mutton", id: "minecraft:cooked_mutton", price: 20, category: "Food" },
  { name: "Cooked Cod", id: "minecraft:cooked_cod", price: 15, category: "Food" },
  { name: "Cooked Salmon", id: "minecraft:cooked_salmon", price: 15, category: "Food" },
  { name: "Bread", id: "minecraft:bread", price: 10, category: "Food" },
  { name: "Golden Apple", id: "minecraft:golden_apple", price: 500, category: "Food" },
  { name: "Enchanted Apple", id: "minecraft:enchanted_golden_apple", price: 5000, category: "Food" },
  { name: "Golden Carrot", id: "minecraft:golden_carrot", price: 50, category: "Food" },
  { name: "Cake", id: "minecraft:cake", price: 100, category: "Food" },
  { name: "Cookie", id: "minecraft:cookie", price: 5, category: "Food" },
  { name: "Sweet Berries", id: "minecraft:sweet_berries", price: 5, category: "Food" },
  { name: "Glow Berries", id: "minecraft:glow_berries", price: 10, category: "Food" },
  { name: "Melon Slice", id: "minecraft:melon_slice", price: 2, category: "Food" },
  { name: "Pumpkin Pie", id: "minecraft:pumpkin_pie", price: 30, category: "Food" },
  { name: "Wheat", id: "minecraft:wheat", price: 10, category: "Food" },
  { name: "Carrot", id: "minecraft:carrot", price: 5, category: "Food" },
  { name: "Potato", id: "minecraft:potato", price: 5, category: "Food" },
  { name: "Sugar Cane", id: "minecraft:sugar_cane", price: 10, category: "Food" },

  // === WOOD & LOGS ===
  { name: "Oak Log", id: "minecraft:oak_log", price: 10, category: "Wood" },
  { name: "Spruce Log", id: "minecraft:spruce_log", price: 10, category: "Wood" },
  { name: "Birch Log", id: "minecraft:birch_log", price: 10, category: "Wood" },
  { name: "Jungle Log", id: "minecraft:jungle_log", price: 10, category: "Wood" },
  { name: "Acacia Log", id: "minecraft:acacia_log", price: 10, category: "Wood" },
  { name: "Dark Oak Log", id: "minecraft:dark_oak_log", price: 10, category: "Wood" },
  { name: "Mangrove Log", id: "minecraft:mangrove_log", price: 15, category: "Wood" },
  { name: "Cherry Log", id: "minecraft:cherry_log", price: 15, category: "Wood" },
  { name: "Bamboo Block", id: "minecraft:bamboo_block", price: 15, category: "Wood" },
  { name: "Crimson Stem", id: "minecraft:crimson_stem", price: 20, category: "Wood" },
  { name: "Warped Stem", id: "minecraft:warped_stem", price: 20, category: "Wood" },

  // === BLOCKS & BUILDING ===
  { name: "Cobblestone", id: "minecraft:cobblestone", price: 2, category: "Blocks" },
  { name: "Stone", id: "minecraft:stone", price: 5, category: "Blocks" },
  { name: "Dirt", id: "minecraft:dirt", price: 2, category: "Blocks" },
  { name: "Grass Block", id: "minecraft:grass", price: 5, category: "Blocks" },
  { name: "Gravel", id: "minecraft:gravel", price: 2, category: "Blocks" },
  { name: "Sand", id: "minecraft:sand", price: 2, category: "Blocks" },
  { name: "Glass", id: "minecraft:glass", price: 5, category: "Blocks" },
  { name: "Obsidian", id: "minecraft:obsidian", price: 100, category: "Blocks" },
  { name: "Deepslate", id: "minecraft:deepslate", price: 5, category: "Blocks" },
  { name: "Cobbled Deepslate", id: "minecraft:cobbled_deepslate", price: 2, category: "Blocks" },
  { name: "Bricks", id: "minecraft:brick_block", price: 20, category: "Blocks" },
  { name: "Stone Bricks", id: "minecraft:stone_bricks", price: 10, category: "Blocks" },
  { name: "Quartz Block", id: "minecraft:quartz_block", price: 50, category: "Blocks" },
  { name: "White Wool", id: "minecraft:wool", price: 15, category: "Blocks" },
  { name: "White Concrete", id: "minecraft:concrete", price: 20, category: "Blocks" },

  // === NATURE & PLANTS ===
  { name: "Oak Sapling", id: "minecraft:oak_sapling", price: 5, category: "Nature" },
  { name: "Spruce Sapling", id: "minecraft:spruce_sapling", price: 5, category: "Nature" },
  { name: "Birch Sapling", id: "minecraft:birch_sapling", price: 5, category: "Nature" },
  { name: "Cherry Sapling", id: "minecraft:cherry_sapling", price: 10, category: "Nature" },
  { name: "Red Tulip", id: "minecraft:red_tulip", price: 5, category: "Nature" },
  { name: "Blue Orchid", id: "minecraft:blue_orchid", price: 10, category: "Nature" },
  { name: "Sunflower", id: "minecraft:sunflower", price: 10, category: "Nature" },
  { name: "Lily Pad", id: "minecraft:waterlily", price: 5, category: "Nature" },
  { name: "Cactus", id: "minecraft:cactus", price: 10, category: "Nature" },
  { name: "Bamboo", id: "minecraft:bamboo", price: 5, category: "Nature" },

  // === MOB DROPS ===
  { name: "Rotten Flesh", id: "minecraft:rotten_flesh", price: 5, category: "Drops" },
  { name: "Bone", id: "minecraft:bone", price: 10, category: "Drops" },
  { name: "Gunpowder", id: "minecraft:gunpowder", price: 20, category: "Drops" },
  { name: "Spider Eye", id: "minecraft:spider_eye", price: 10, category: "Drops" },
  { name: "String", id: "minecraft:string", price: 10, category: "Drops" },
  { name: "Ender Pearl", id: "minecraft:ender_pearl", price: 50, category: "Drops" },
  { name: "Blaze Rod", id: "minecraft:blaze_rod", price: 50, category: "Drops" },
  { name: "Slime Ball", id: "minecraft:slime_ball", price: 25, category: "Drops" },
  { name: "Leather", id: "minecraft:leather", price: 20, category: "Drops" },
  { name: "Feather", id: "minecraft:feather", price: 5, category: "Drops" },
  { name: "Ink Sac", id: "minecraft:ink_sac", price: 10, category: "Drops" },

  // === REDSTONE & TOOLS ===
  { name: "Redstone Dust", id: "minecraft:redstone", price: 10, category: "Redstone" },
  { name: "Restone Torch", id: "minecraft:redstone_torch", price: 15, category: "Redstone" },
  { name: "Repeater", id: "minecraft:repeater", price: 30, category: "Redstone" },
  { name: "Comparator", id: "minecraft:comparator", price: 50, category: "Redstone" },
  { name: "Observer", id: "minecraft:observer", price: 50, category: "Redstone" },
  { name: "Piston", id: "minecraft:piston", price: 60, category: "Redstone" },
  { name: "Sticky Piston", id: "minecraft:sticky_piston", price: 80, category: "Redstone" },
  { name: "Hopper", id: "minecraft:hopper", price: 100, category: "Redstone" },
  { name: "Dispenser", id: "minecraft:dispenser", price: 50, category: "Redstone" },
  { name: "Dropper", id: "minecraft:dropper", price: 40, category: "Redstone" },
  { name: "TNT", id: "minecraft:tnt", price: 150, category: "Redstone" },
  { name: "Slime Block", id: "minecraft:slime", price: 250, category: "Redstone" },
  { name: "Honey Block", id: "minecraft:honey_block", price: 250, category: "Redstone" },
];
